global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'pacman-sync-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # HAProxy metrics
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8404']
    metrics_path: '/stats'
    params:
      stats: ['']
    scrape_interval: 30s

  # Pacman Sync Utility health endpoints
  - job_name: 'pacman-sync-health'
    static_configs:
      - targets: 
        - 'haproxy:8080'
    metrics_path: '/health/detailed'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    
  # Individual server instances (when not behind load balancer)
  - job_name: 'pacman-sync-servers'
    static_configs:
      - targets:
        - 'pacman-sync-server_1:8080'
        - 'pacman-sync-server_2:8080'
        - 'pacman-sync-server_3:8080'
    metrics_path: '/health/detailed'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL monitoring (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 30s

  # Docker container metrics (if using cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 30s